{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-28T21:24:17Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: release 0.0.36
    sha: ff0cacc550e320ffddb7888f9f70f6b5e6bdb04c
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: add variables
    sha: 26cbd0f70af41fd79c97d01f77db4b4f6a1432b1
  - author:
      email: salaboy@gmail.com
      name: salaboy
    branch: master
    committer:
      email: salaboy@gmail.com
      name: salaboy
    message: |
      updating profiles sso and tracing
    sha: 64558b1a42c195f04ab05311a4b232aa84de1589
  gitHttpUrl: https://github.com/salaboy/fmtok8s-c4p-rest
  gitOwner: salaboy
  gitRepository: fmtok8s-c4p-rest
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/salaboy/fmtok8s-c4p-rest/releases/tag/v0.0.37
  version: v0.0.37
status: {}
 
{{- end }}
